### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by v4u9h4n** [mauroalderete/virtualmic-pulseaudio#5]
Hello, thanks for making this, how do I use it? Not sure what to do once it is installed.

**Comment by mauroalderete** [comment]
Hi, I'm glad you liked the project.

I've added more information on how to use it and how it works in the readme.

Also, I wrote some practical uses based on my day-to-day experience.

If you have more questions or there is something that is not very clear, ask me without hesitation. Luck!
