### ISSUE TITLE
Not a question - a Thank You !!

### ISSUE THREAD

**Issue by fredt34** [mauroalderete/virtualmic-pulseaudio#7]
Hi,

As I'm too lazy to create an account on the OBS forum: Just Thank You !! 

Now I can make marketing Meet Calls with high quality !

Fred

**Comment by mauroalderete** [comment]
Hi Fred!

It's sound great!!

This project arose because I was looking for the same... now I am combining virtualmic with Whisper AI to get transcriptions in real-time in my meets.

I'm glad it's handy for you!
